- name: "Vault | Check stats of job file"
  ansible.builtin.stat:
    path: "{{ nomad_job_files_dir }}/{{ job_name }}.hcl"
  register: job

- name: "Vault | Write secret for app credentials"
  ansible.builtin.import_role:
    name: hashistack.vault.operate
  vars:
    role_action: write
    vault_secret_path: "apps/data/{{ fqdn }}"
    vault_secret:
      data:
        vault_token: "{{ vault_token }}"
        vault_root_token: "{{ vault_root_token }}"
  when:
    - vault_state == "write"
    - not vault_token_renew_self

- name: "Vault | Write secret for app credentials"
  ansible.builtin.import_role:
    name: hashistack.vault.operate
  vars:
    role_action: write
    vault_secret_path: "apps/data/{{ fqdn }}"
    vault_secret:
      data:
        vault_token: "{{ vault_token }}"
  when:
    - vault_state == "write"
    - vault_token_renew_self
