---
# tasks file for Vault Auto-renew

- name: "Vault | Checks if mandatory variables are sets"
  ansible.builtin.include_tasks: checks.yml

- name: "Vault | Deploy with {{ install_method }}"
  ansible.builtin.import_role:
    name: hashistack.deploy.nomad
  when: install_method == "nomad"
