- name: "Docker Install | Mandatories packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - lsb-release

- name: "Docker Install | Add repository"
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: true
  notify: Docker_update_apt_cache

- name: "Docker Install | flush_handlers"
  ansible.builtin.meta: flush_handlers

- name: "Docker Install | Uninstall OS defaults Docker packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: "Docker Install | Install Docker packages from official repository"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: "Docker Install | Pip packages"
  ansible.builtin.pip:
    name: "docker"
    state: present

- name: "Docker Install | Add user to docker group"
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  notify: "Docker_restart"

- name: "Docker Install | Copy config.json"
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ docker_private_registry_config }}"
    owner: root
    group: root
    mode: '0600'
  when: docker_private_registry_state
  notify: "Docker_restart"

- name: "Docker Install | Copy daemon.json for DNS resolution"
  ansible.builtin.template:
    src: daemon.json.j2
    dest: "{{ docker_conf_dir }}/daemon.json"
    owner: root
    group: root
    mode: '0600'
  when: docker_dns_configuration
  notify: "Docker_restart"

- name: "Docker Install | Restart Docker"
  ansible.builtin.meta: flush_handlers
