- name: "RunC | Check if go already installed"
  ansible.builtin.stat:
    path: /usr/local/go/bin/go
  register: go_installed

- name: "RunC | Install Go"
  ansible.builtin.import_role:
    name: hashistack.go.install
  when: not go_installed.stat.exists

- name: "RunC | Git clone runc repository"
  ansible.builtin.git:
    repo: 'https://github.com/opencontainers/runc.git'
    dest: "/usr/local/go/src/github.com/opencontainers/runc"
    version: HEAD

- name: "RunC | Make runc"
  community.general.make:
    chdir: "/usr/local/go/src/github.com/opencontainers/runc"
    params:
      PATH: "$PATH:/usr/local/go/bin"

- name: "RunC | Copy runc executable"
  ansible.builtin.copy:
    src: /usr/local/go/src/github.com/opencontainers/runc/runc
    dest: /usr/bin/runc
    remote_src: true
    mode: '0755'

- name: RunC | Change chmod runc executable
  ansible.builtin.file:
    path: "/usr/bin/runc"
    owner: root
    group: root
    mode: '0755'
