- name: "Nomad Install | Install binary"
  ansible.builtin.apt:
    name: nomad
    update_cache: true
  when: nomad_install_version is not defined

- name: "Nomad Install | Install binary"
  ansible.builtin.apt:
    name: "nomad={{ nomad_install_version }}-1"
    update_cache: true
  when: nomad_install_version is defined

- name: "Nomad Install | Create Nomad logs and data directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ nomad_install_group }}"
    owner: "{{ nomad_install_user }}"
    mode: '0755'
  loop:
    - /var/log/nomad
    - /opt/nomad

- name: "Nomad Install | Prevent Nomad from being upgraded"
  ansible.builtin.dpkg_selections:
    name: nomad
    selection: hold

- name: "Nomad Install | Add user nomad to group {{ hashistack_group }}"
  ansible.builtin.user:
    name: nomad
    groups: nomad,{{ hashistack_group }}
    append: true
  when: nomad_node_role == 'server'

- name: "Nomad Install | Create systemd override directory"
  ansible.builtin.file:
    path: "/etc/systemd/system/nomad.service.d"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"

- name: Nomad Install | Template for systemd override
  ansible.builtin.template:
    src: "override.conf.j2"
    dest: "/etc/systemd/system/nomad.service.d/override.conf"
    mode: "0644"

- name: "Nomad Install | Playbook's template"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/root/{{ item }}"
    mode: "0644"
  loop:
    - nomad_stop.yml
  when: nomad_install_mode == 'single'

- name: "Nomad Install | Daemon reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true
