- name: "Nomad SystemD tuning | Create systemd override directory"
  ansible.builtin.file:
    path: "/etc/systemd/system/nomad.service.d"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"

- name: Nomad SystemD tuning | Template for systemd override
  ansible.builtin.template:
    src: "override.conf.j2"
    dest: "/etc/systemd/system/nomad.service.d/override.conf"
    mode: '0644'

- name: "Nomad SystemD tuning | Playbook's template"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/root/{{ item }}"
    mode: '0644'
  loop:
    - nomad_stop.yml
  when: nomad_install_mode == 'single'

- name: "Nomad SystemD tuning | Daemon reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true
