- name: Podman | Create conf directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ role_user }}"
    group: "{{ role_user }}"
    recurse: true
  loop:
    - "/etc/containers"
    - "/run/containers/storage"
    - "/run/podman"
    - "/var/lib/containers/storage"

- name: Podman | Templates Podman configurations files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/containers/{{ item.dest }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: '0755'
  loop:
    - { src: "containers.conf.j2", dest: "containers.conf"}
    - { src: "storage.conf.j2", dest: "storage.conf"}
    - { src: "registries.conf.j2", dest: "registries.conf"}
    - { src: "default-policy.json.j2", dest: "policy.json"}

- name: Podman | Retreive GitHub latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/containers/podman/releases/latest
    body_format: json
  register: tag

- name: Podman | Unarchive Podman
  ansible.builtin.unarchive:
    src: "https://github.com/containers/podman/archive/refs/tags/{{ tag.json.tag_name }}.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Podman | Make
  ansible.builtin.command: make
  args:
    chdir: "/tmp/podman-{{ tag.json.tag_name | replace('v', '') }}"
  environment:
    BUILDTAGS: "{{ podman_buildtags }}"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin"
  register: podman_make
  changed_when: podman_make.rc != 0

- name: Podman | Make install
  ansible.builtin.command: make install
  args:
    chdir: "/tmp/podman-{{ tag.json.tag_name | replace('v', '') }}"
  environment:
    BUILDTAGS: "{{ podman_buildtags }}"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin"
  register: podman_make_install
  changed_when: podman_make_install.rc != 0

- name: Podman | Template systemd service
  ansible.builtin.template:
    src: podman.service-root.j2
    dest: /etc/systemd/system/podman.service
    owner: "{{ role_user }}"
    group: "{{ role_user }}"
    mode: '0755'
  notify: podman_restart
