---
# tasks file for podman

- name: "Podman | Install from source"
  ansible.builtin.include_tasks: install.yml

- name: "Podman | Configure for rootless usage"
  ansible.builtin.include_tasks: config_rootless.yml
  when: podman_rootless

- name: "Podman | Configure for root usage"
  ansible.builtin.include_tasks: config_root.yml
  when: not podman_rootless
