---
# defaults file for operate

# General
vault_http_scheme: "{% if vault_tls == true %}https{% else %}http{% endif %}"
vault_http_ip: "127.0.0.1"
vault_http_port: 8200
vault_unsecure: false
vault_conf_dir: "/etc/vault.d"
vault_consul_backend: true

vault_operate_log_level: info
vault_operate_prometheus_retention_time: "24h"

check_online_version: true

vault_operate_dc_name: "dc1"

vault_version: 1.15.1

binary_path: "/usr/bin"
vault_path: "{{ binary_path }}"

#vault_url: "http://127.0.0.1:8200"
vault_root_token: ""
vault_secret_path: "apps/data/{{ fqdn }}" # /data/ is mandatory, vault specify

vault_auth_method_type: jwt
vault_auth_method_name: jwt-nomad

# TLS
vault_operate_tls_ca_host: localhost
vault_operate_tls_ca_host_dir: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls"
vault_operate_tls_ca_pubkey: "hashistack-ca.pem"
vault_operate_tls_ca_privatekey: "hashistack-ca-key.pem"
vault_operate_tls_ca_provider: "ownca"

vault_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"

vault_operate_tls_cert: "{{ vault_operate_dc_name }}-server-vault.pem"
vault_operate_tls_privatekey: "{{ vault_operate_dc_name }}-server-vault.key"

# Upgrade
vault_extract_checksum_cmd: 'grep "vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip" /tmp/vault_{{ vault_version }}_SHA256SUMS | sed -n "s/^\(.*\)  vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip/\1/p"'

# Read
vault_secret_to_get: "password"

# Write

# Role rules
# vault_role_name: ""
# vault_role_name: "backups-jobs"
vault_role_role_type: "jwt"
# vault_role_policies: '["backups-jobs"]'
vault_role_user_claim: "/nomad_job_id"
vault_role_bound_audiences: "vault.io"
vault_role_claim_mapping_nomad_namespace: "nomad_namespace"
vault_role_claim_mapping_nomad_job_id: "nomad_job_id"
vault_role_claim_mapping_nomad_task: "nomad_task"
vault_role_token_type: "service"
vault_role_token_period: "30m"
# vault_role_token_policies: "backups-jobs"
vault_role_token_explicit_max_ttl: 0

# Example:
vault_secret:
  data: # /data/ is mandatory, vault specify
    fqdn: "{{ fqdn }}"
    admin: "{{ admin }}"
    password: "{{ password }}"

# Token
nomad_token: true
nomad_conf_dir: "/etc/nomad.d"
token_role_name: nomad
token_ttl: "768h"
vault_policies:
  - nomad-server
  - access-creds

# Create KV
vault_kv_name: "apps"

# Renew
# vault_token_renew_token:
vault_token_renew_ttl: "768h"
vault_token_renew_self: true

# Backup
vault_backup_basename: "vault_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}"

consul_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"

vault_consul_backend_http_scheme: "https"
vault_consul_backend_http_ip: "127.0.0.1"
vault_consul_backend_http_port: 8501
vault_consul_backend_tls_cert: "{{ vault_operate_dc_name }}-server-consul.pem"
vault_consul_backend_tls_privatekey: "{{ vault_operate_dc_name }}-server-consul.key"
