---
# tasks file for backup

- name: "Vault Unseal | Install pip module"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - ansible

- name: "Vault Unseal | Copy auto-unseal playbook"
  ansible.builtin.template:
    src: "vault_unseal.yml.j2"
    dest: "/root/vault_unseal.yml"
    mode: "0644"

- name: "Vault Unseal | Copy service systemd file"
  ansible.builtin.template:
    src: vault-unseal.service.j2
    dest: /lib/systemd/system/vault-unseal.service
    owner: root
    group: root
    mode: '0644'

- name: "Vault Unseal | Copy override conf"
  ansible.builtin.lineinfile:
    path: "/etc/systemd/system/vault.service.d/override.conf"
    insertafter: '[Unit]'
    line: 'Wants=vault-unseal.service'

- name: "Vault Unseal | Register systemd service"
  ansible.builtin.systemd_service:
    name: vault-unseal.service
    enabled: true
    daemon_reload: true
