- name: "Consul | TLS Configuration for servers"
  ansible.builtin.import_role:
    name: hashistack.certificate.create
    tasks_from: client
  vars:
    host_certificate_dir: "{{ consul_install_tls_ca_host_dir }}"
    ca_host_dir: "{{ consul_install_tls_ca_host_dir }}"
    ca_pubkey: "{{ consul_install_tls_ca_pubkey }}"
    ca_privatekey: "{{ consul_install_tls_ca_privatekey }}"
    ca_provider: "{{ consul_install_tls_ca_provider }}"
    ca_host: "{{ consul_install_tls_ca_host }}"
    cert: "{{ consul_install_tls_cert_server }}"
    client_privatekey: "{{ consul_install_tls_privatekey_server }}"
    common_name: "{{ consul_install_tls_common_name_server }}"
    subject_alt_name: "{{ consul_install_tls_subject_alt_name_server }}"
  when: not cert_tls_server_present.stat.exists or
        (cert_tls_server_present.stat.exists and not tls_check_server.valid_at.delay)
  become: false
  delegate_to: localhost
  run_once: true

- name: "Nomad | TLS Configuration for Clients"
  ansible.builtin.import_role:
    name: hashistack.certificate.create
    tasks_from: client
  vars:
    host_certificate_dir: "{{ consul_install_tls_ca_host_dir }}"
    ca_host_dir: "{{ consul_install_tls_ca_host_dir }}"
    ca_pubkey: "{{ consul_install_tls_ca_pubkey }}"
    ca_privatekey: "{{ consul_install_tls_ca_privatekey }}"
    ca_provider: "{{ consul_install_tls_ca_provider }}"
    ca_host: "{{ consul_install_tls_ca_host }}"
    cert: "{{ consul_install_tls_cert_client }}"
    client_privatekey: "{{ consul_install_tls_privatekey_client }}"
    common_name: "{{ consul_install_tls_common_name_client }}"
    subject_alt_name: "{{ consul_install_tls_subject_alt_name_client }}"
  when:
    - consul_install_mode == 'cluster'
    - >
      ( groups[consul_deploy_cluster_name] | map('extract', hostvars) |
        selectattr('consul_node_role', 'equalto', 'client') |
        map(attribute='inventory_hostname') | length ) >= 1
    - >
      ( not ( groups[consul_deploy_cluster_name] | map('extract', hostvars) |
              selectattr('consul_node_role', 'equalto', 'client') |
              map(attribute='cert_tls_client_present.stat.exists') | list | first ) ) or
      ( ( groups[consul_deploy_cluster_name] | map('extract', hostvars) |
            selectattr('consul_node_role', 'equalto', 'client') |
            map(attribute='cert_tls_client_present.stat.exists') | list | first ) and
        not ( groups[consul_deploy_cluster_name] | map('extract', hostvars) |
              selectattr('consul_node_role', 'equalto', 'client') |
              map(attribute='tls_check_client.valid_at.delay') | list | first ) )
  become: false
  delegate_to: localhost
  run_once: true

- name: "Consul | Copy cert server on nodes - {{ consul_install_tls_cert_server }} "
  ansible.builtin.copy:
    src: "{{ consul_install_tls_ca_host_dir }}/{{ consul_install_tls_cert_server }}"
    dest: "{{ consul_install_tls_host_certificate_dir }}/{{ consul_install_tls_cert_server }}"
    owner: "root"
    group: "{{ hashistack_group }}"
    mode: "0640"
  when: consul_node_role == 'server' or consul_node_role == 'both'

- name: "Consul | Copy cert private server key on nodes - {{ consul_install_tls_privatekey_server }}"
  ansible.builtin.copy:
    src: "{{ consul_install_tls_ca_host_dir }}/{{ consul_install_tls_privatekey_server }}"
    dest: "{{ consul_install_tls_host_certificate_dir }}/{{ consul_install_tls_privatekey_server }}"
    owner: "root"
    group: "{{ hashistack_group }}"
    mode: "0640"
  when: consul_node_role == 'server' or consul_node_role == 'both'

- name: "Consul | Copy cert client key on nodes - {{ consul_install_tls_cert_client }}"
  ansible.builtin.copy:
    src: "{{ consul_install_tls_ca_host_dir }}/{{ consul_install_tls_cert_client }}"
    dest: "{{ consul_install_tls_host_certificate_dir }}/{{ consul_install_tls_cert_client }}"
    owner: "root"
    group: "{{ hashistack_group }}"
    mode: "0640"
  when: consul_node_role == 'client'

- name: "Consul | Copy cert private client key on nodes - {{ consul_install_tls_privatekey_client }}"
  ansible.builtin.copy:
    src: "{{ consul_install_tls_ca_host_dir }}/{{ consul_install_tls_privatekey_client }}"
    dest: "{{ consul_install_tls_host_certificate_dir }}/{{ consul_install_tls_privatekey_client }}"
    owner: "root"
    group: "{{ hashistack_group }}"
    mode: "0640"
  when: consul_node_role == 'client'
