---
# tasks file for install

- name: "Consul | Commons tasks"
  ansible.builtin.include_tasks: "01_commons_tasks.yml"

- name: "Consul | Generate CA Cert"
  ansible.builtin.include_tasks: "02_ca_cert.yml"
  when:
    - consul_tls
    - not cert_ca_tls_priv_present.stat.exists

- name: "Consul | TLS certs configuration"
  ansible.builtin.include_tasks: "03_tls_certs.yml"
  when: consul_tls

- name: "Consul | Install"
  ansible.builtin.include_tasks: "04_install.yml"

- name: "Consul | ACL Configuration"
  ansible.builtin.include_tasks: "05_acl.yml"
  when: consul_acl

- name: "Consul | Agent Clients Configuration"
  ansible.builtin.include_tasks: "06_consul_agent_clients.yml"

- name: "Consul | service.consul DNS resolution"
  ansible.builtin.include_tasks: "07_dns.yml"
  when: consul_install_dns_resolution

- name: "Consul | Firewall Configuration"
  ansible.builtin.include_tasks: "08_firewall.yml"
  when: consul_install_firewall

- name: "Consul | Replace systemd custom service file"
  ansible.builtin.copy:
    src: "consul.service"
    dest: "/usr/lib/systemd/system/consul.service"
    mode: '0644'
