- name: "Consul Token | Get tokens list"
  ansible.builtin.uri:
    url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/acl/tokens"
    method: GET
    ca_path: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}{% endif %}"
    client_key: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}{% endif %}"
    headers:
      X-Consul-Token: "{% if consul_acl %}{{ consul_global_management_token }}{% endif %}"
    return_content: true
    status_code:
      - 200
  register: consul_tokens_list_raw

- name: "Consul Token | Create tokens list"
  ansible.builtin.set_fact:
    consul_tokens_list: "{{ consul_tokens_list_raw.json | community.general.json_query('[*].Description') | string }}"

- name: "Consul Token | Token creation - {{ consul_token_name }}"
  ansible.builtin.uri:
    url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/acl/token"
    method: PUT
    ca_path: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}{% endif %}"
    client_key: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}{% endif %}"
    headers:
      X-Consul-Token: "{% if consul_acl %}{{ consul_global_management_token }}{% endif %}"
    body: |
        {
          "Description": "{{ consul_token_description | default(consul_policy_name) }}",
          "Policies": [
            {
              "Name": "{{ consul_policy_name | lower }}"
            }
          ]
        }
    body_format: json
    status_code:
      - 200
  register: consul_new_token_name
  when: 'consul_token_name not in consul_tokens_list'

- name: "Consul Token | Token in host_vars with TLS and ACL - {{ consul_token_name }}"
  ansible.builtin.blockinfile:
    path: "{{ hashistack_creds_file }}"
    marker: "#<!-- {mark} CONSUL {{ consul_token_name | upper }} TOKEN ANSIBLE MANAGED BLOCK -->"
    block: |
      consul_{{ consul_token_name }}_token: "{{ consul_new_token_name.json.SecretID }}"
    create: true
    mode: "0644"
  delegate_to: localhost
  become: false
  when: 'consul_token_name not in consul_tokens_list'

- name: "Consul Token | Set token for the rest of the play - {{ consul_token_name }}"
  ansible.builtin.set_fact:
    consul_{{ consul_token_name }}_token: "{{ consul_new_token_name.json.SecretID }}"
  when: 'consul_token_name not in consul_tokens_list'

- name: "Consul Token | Already create"
  ansible.builtin.debug:
    msg: "Token {{ consul_token_name }} already create"
  when: consul_token_name in consul_tokens_list
