---
- name: "Consul | Upgrade | Install requiered binary"
  ansible.builtin.apt:
    name: unzip
    update_cache: true

- name: "Consul | Upgrade | Retrieve brut list from hashicorp.com"
  ansible.builtin.uri:
    url: "https://releases.hashicorp.com/consul/"
    return_content: true
  register: consul_brut_list
  when: check_online_version

- name: "Consul | Upgrade | Extract version number"
  ansible.builtin.set_fact:
    consul_version: '{{ consul_brut_list.content | regex_search("consul_[\d.]{3,}<") | regex_replace("<", "") | regex_search("\d.*") }}'
  when: check_online_version

- name: "Consul | Upgrade | Check Consul installed version"
  ansible.builtin.command: consul version
  register: consul_installed_version
  changed_when: consul_installed_version.rc != 0

- name: "Consul | Upgrade | Download Consul zip"
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: /tmp
    mode: '0440'
  when: consul_version is not in consul_installed_version.stdout

- name: "Consul | Upgrade | Download checksum"
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_SHA256SUMS
    dest: /tmp/consul_{{ consul_version }}_SHA256SUMS
    mode: '0440'
  when: consul_version is not in consul_installed_version.stdout

- name: "Consul | Upgrade | Get checksum of Consul zip"
  ansible.builtin.stat:
    path: /tmp/consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    checksum_algorithm: sha256
    get_checksum: true
  register: zip_checkum
  when: consul_version is not in consul_installed_version.stdout

- name: "Consul | Upgrade | Get checksum of Consul official repo"
  ansible.builtin.shell: "{{ consul_extract_checksum_cmd }}"
  register: checksum_output
  changed_when: checksum_output.rc != 0
  when: consul_version is not in consul_installed_version.stdout

- name: "Consul | Upgrade | Verify sha256sum"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when:
    - consul_version is not in consul_installed_version.stdout
    - zip_checkum.stat.checksum != checksum_output.stdout

- name: "Consul | Upgrade | Download and extract new version"
  ansible.builtin.unarchive:
    src: "/tmp/consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: "{{ consul_path }}"
    remote_src: true
  notify: "Consul_restart"
  when: consul_version is not in consul_installed_version.stdout

- name: "Consul | Upgrade | Clean tmp files"
  ansible.builtin.file:
    path: "{{ item }}"
  loop:
    - /tmp/consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    - /tmp/consul_{{ consul_version }}_SHA256SUMS
  when: consul_version is not in consul_installed_version.stdout
