---
- name: "Nomad | Upgrade | Install requiered binary"
  ansible.builtin.apt:
    name: unzip
    update_cache: true

- name: "Nomad | Upgrade | Retrieve brut list from hashicorp.com"
  ansible.builtin.uri:
    url: "https://releases.hashicorp.com/nomad/"
    return_content: true
  register: nomad_brut_list
  when: check_online_version

- name: "Nomad | Upgrade | Extract version number"
  ansible.builtin.set_fact:
    nomad_version: '{{ nomad_brut_list.content | regex_search("nomad_[\d.]{3,}<") | regex_replace("<", "") | regex_search("\d.*") }}'
  when: check_online_version

- name: "Nomad | Upgrade | Check Nomad installed version"
  ansible.builtin.command: nomad version
  register: nomad_installed_version
  changed_when: nomad_installed_version.rc != 0

- name: "Nomad | Upgrade | Download Nomad zip"
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: /tmp
    mode: '0440'
  when: nomad_version is not in nomad_installed_version.stdout

- name: "Nomad | Upgrade | Download checksum"
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_SHA256SUMS
    dest: /tmp/nomad_{{ nomad_version }}_SHA256SUMS
    mode: '0440'
  when: nomad_version is not in nomad_installed_version.stdout

- name: "Nomad | Upgrade | Get checksum of Nomad zip"
  ansible.builtin.stat:
    path: /tmp/nomad_{{ nomad_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    checksum_algorithm: sha256
    get_checksum: true
  register: zip_checkum
  when: nomad_version is not in nomad_installed_version.stdout

- name: "Nomad | Upgrade | Get checksum of Nomad official repo"
  ansible.builtin.shell: "{{ nomad_extract_checksum_cmd }}"
  register: checksum_output
  changed_when: checksum_output.rc != 0
  when: nomad_version is not in nomad_installed_version.stdout

- name: "Nomad | Upgrade | Verify sha256sum"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when:
    - nomad_version is not in nomad_installed_version.stdout
    - zip_checkum.stat.checksum != checksum_output.stdout

- name: "Nomad | Upgrade | Download and extract new version"
  ansible.builtin.unarchive:
    src: "/tmp/nomad_{{ nomad_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: "{{ nomad_path }}"
    remote_src: true
  notify: "Nomad_restart"
  when: nomad_version is not in nomad_installed_version.stdout

- name: "Nomad | Upgrade | Clean tmp files"
  ansible.builtin.file:
    path: "{{ item }}"
  loop:
    - /tmp/nomad_{{ nomad_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    - /tmp/nomad_{{ nomad_version }}_SHA256SUMS
  when: nomad_version is not in nomad_installed_version.stdout
