- name: "Nomad Variable | Put variable"
  ansible.builtin.uri:
    url: "{{ nomad_http_scheme }}://{{ nomad_http_ip }}:{{ nomad_http_port }}/v1/var/{{ nomad_var_path }}"
    ca_path: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_cert }}{% endif %}"
    client_key: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_privatekey }}{% endif %}"
    method: PUT
    headers:
      X-Nomad-Token: "{% if nomad_acl %}{{ nomad_management_token | default(ansible_local.nomad_management_token.nomad_management_token) }}{% endif %}"
    body: |
      {
        "Namespace": "{{ nomad_namespace | default('default') }}",
        "Path": "{{ nomad_var_path }}",
        "Items": {
          {% for item in nomad_var_list %}
          "{{ item.key }}": "{{ item.value }}"{% if not loop.last %},{% endif %}
          {% endfor %}
        }
      }
    body_format: json
    status_code:
      - 200
