- name: "Vault Install | Install binary"
  ansible.builtin.apt:
    name: vault
    update_cache: true
  when: vault_install_version is not defined

- name: "Vault Install | Create raft directory"
  ansible.builtin.file:
    path: "{{ vault_install_storage_dir }}"
    state: directory
    mode: '0755'
    owner: "vault"
    group: "vault"

- name: "Vault Install | Install binary"
  ansible.builtin.apt:
    name: "vault={{ vault_install_version }}-1"
    update_cache: true
  when: vault_install_version is defined

- name: "Vault Install | Prevent Vault from being upgraded"
  ansible.builtin.dpkg_selections:
    name: vault
    selection: hold

- name: "Vault Install | Copy config file"
  ansible.builtin.template:
    src: "vault.hcl.j2"
    dest: "{{ vault_conf_dir }}/vault.hcl"
    owner: vault
    group: vault
    mode: '0644'

- name: "Vault Install | Create Vault logs directory"
  ansible.builtin.file:
    path: "/var/log/vault"
    state: directory
    mode: '0755'
    owner: "vault"
    group: "vault"

- name: "Vault Install | Create systemd override directory"
  ansible.builtin.file:
    path: "/etc/systemd/system/vault.service.d"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"

- name: "Vault Install | Insert override settings for SystemD"
  ansible.builtin.blockinfile:
    path: "/etc/systemd/system/vault.service.d/override.conf"
    marker: "# <!-- {mark} CONSUL WAIT -->"
    block: |
      [Unit]
      After=consul.service
    mode: '0644'
    create: true
  register: vault_override_insert

- name: "Vault Install | Start Vault"
  ansible.builtin.systemd_service:
    state: restarted
    name: vault
    enabled: true
    daemon_reload: true
  when: vault_override_insert.changed

- name: "Vault Install | Wait for Vault restarted"
  ansible.builtin.wait_for:
    host: "{{ vault_install_http_ip }}"
    port: "{{ vault_install_http_port }}"
