---
# tasks file for Vault Install

- name: "Vault | Commons tasks"
  ansible.builtin.include_tasks: "01_commons_tasks.yml"

- name: "Consul | Generate CA Cert"
  ansible.builtin.include_tasks: "02_ca_cert.yml"
  when:
    - vault_tls
    - not cert_ca_tls_priv_present.stat.exists

- name: "Consul | TLS certs configuration"
  ansible.builtin.include_tasks: "03_tls_certs.yml"
  when:
    - vault_tls
    - not cert_tls_present.stat.exists or (cert_tls_present.stat.exists and not tls_check.valid_at.delay)

- name: "Vault | Consul ACL"
  ansible.builtin.include_tasks: "04_consul_acl.yml"
  when: vault_acl

- name: "Vault | Install"
  ansible.builtin.include_tasks: "05_install.yml"

- name: "Vault | Configuration"
  ansible.builtin.include_tasks: "06_configuration.yml"

- name: "Vault | Firewall Configuration"
  ansible.builtin.include_tasks: "07_firewall.yml"
  when: vault_install_firewall

- name: "Vault | Create KV"
  ansible.builtin.import_role:
    name: hashistack.vault.operate
    tasks_from: kv_engine_create
  run_once: true

- name: Vault | Install Vault autounseal
  ansible.builtin.import_role:
    name: hashistack.vault.autounseal

- name: "Vault | Replace systemd custom service file"
  ansible.builtin.copy:
    src: "vault.service"
    dest: "/usr/lib/systemd/system/vault.service"
    mode: '0644'
