---
# defaults file for operate

# General
consul_http_scheme: "{% if consul_tls == true %}https{% else %}http{% endif %}"
consul_http_ip: "127.0.0.1"
consul_http_port: "{% if consul_tls == true %}8501{% else %}8500{% endif %}"

check_online_version: true
consul_config_file: "/etc/consul.d/config.json"
consul_config_dir: "/etc/consul.d"

consul_operate_dc_name: "dc1"

consul_version: 1.16.2

binary_path: "/usr/bin"
consul_path: "{{ binary_path }}"

# hashistack_creds_file: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/hashistack.yml"

# DNS (configure systemd-resolved)
consul_dns_systemd_resolved_conf_dir: "/etc/systemd/resolved.conf.d"
consul_dns_ip: 127.0.0.1
consul_dns_port: 8600
consul_dns_domain: "~consul"
consul_dns_listerner: "false"
consul_dns_listerner_extra:
 - 172.17.0.1
 - 172.26.64.1

# TLS
consul_operate_tls_ca_host: localhost
consul_operate_tls_ca_host_dir: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls"
consul_operate_tls_ca_pubkey: "hashistack-ca.pem"
consul_operate_tls_ca_privatekey: "hashistack-ca-key.pem"
consul_operate_tls_ca_provider: "ownca"

consul_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"

consul_operate_tls_cert: "{{ consul_operate_dc_name }}-server-consul.pem"
consul_operate_tls_privatekey: "{{ consul_operate_dc_name }}-server-consul.key"

consul_operate_tls_common_name: "*.{{ consul_operate_dc_name }}.consul"
consul_operate_tls_subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.dc1.consul"

# Upgrade
consul_extract_checksum_cmd: 'grep "consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip" /tmp/consul_{{ consul_version }}_SHA256SUMS | sed -n "s/^\(.*\)  consul_{{ consul_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip/\1/p"'

# Backup
consul_backup_basename: "consul_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}"

# Service
fqdn: "hostname.com"

consul_service_name: "{{ fqdn | replace('.', '-') }}"
# consul_service_port: "12700"
# consul_service_address: 172.17.0.1

consul_operate_enabletagoverride: "false"

# Traefik Tags
traefik_tags: true
# traefik_access: "internal"
service_name: "{{ fqdn | replace('.', '-') }}"

traefik_consul_connect: false
traefik_noindex: true

htaccess_user: "admin"
htaccess_password: "123456"
allow_ip: 207.180.232.70

security_basic_auth: false
security_ip: false

metrics_exporter: true
app_name: none
