- name: "Vault | Backup | Create backup dir"
  ansible.builtin.file:
    path: "{{ vault_conf_dir }}/backup"
    state: directory
    mode: "0755"

- name: "Vault | Backup | Generate backup for Consul backend"
  ansible.builtin.shell: "consul snapshot save {{ vault_backup_basename }}.snap"
  args:
    chdir: "{{ vault_conf_dir }}/backup"
  environment:
    CONSUL_HTTP_ADDR: "{{ vault_consul_backend_http_ip }}:{{ vault_consul_backend_http_port }}"
    CONSUL_HTTP_SSL: "true"
    CONSUL_HTTP_TOKEN: "{{ consul_global_management_token }}"
    CONSUL_CACERT: "{{ consul_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    CONSUL_CLIENT_CERT: "{{ consul_operate_tls_host_certificate_dir }}/{{ vault_consul_backend_tls_cert }}"
    CONSUL_CLIENT_KEY: "{{ consul_operate_tls_host_certificate_dir }}/{{ vault_consul_backend_tls_privatekey }}"
  register: vault_backup_result
  failed_when: vault_backup_result.rc != 0
  when: vault_consul_backend

- name: "Vault | Backup | Generate backup"
  ansible.builtin.shell: "vault operator raft snapshot save {{ vault_backup_basename }}.snap"
  args:
    chdir: "{{ vault_conf_dir }}/backup"
  environment:
    VAULT_ADDR: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
    VAULT_CACERT: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    VAULT_CLIENT_CERT: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    VAULT_CLIENT_KEY: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
  register: vault_backup_result
  failed_when: vault_backup_result.rc != 0
  when: not vault_consul_backend
