---
- name: "Vault | Upgrade | Install requiered binary"
  ansible.builtin.apt:
    name: unzip
    update_cache: true
  when: vault_node_role == 'server'

- name: "Vault | Upgrade | Retrieve brut list from hashicorp.com"
  ansible.builtin.uri:
    url: "https://releases.hashicorp.com/vault/"
    return_content: true
  register: vault_brut_list
  when:
    - vault_node_role == 'server'
    - check_online_version

- name: "Vault | Upgrade | Extract version number"
  ansible.builtin.set_fact:
    vault_version: '{{ vault_brut_list.content | regex_search("vault_[\d.]{3,}<") | regex_replace("<", "") | regex_search("\d.*") }}'
  when:
    - vault_node_role == 'server'
    - check_online_version

- name: "Vault | Upgrade | Check Vault installed version"
  ansible.builtin.command: vault version
  register: vault_installed_version
  changed_when: vault_installed_version.rc != 0
  when: vault_node_role == 'server'

- name: "Vault | Upgrade | Download Vault zip"
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: /tmp
    mode: '0440'
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | Download checksum"
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_SHA256SUMS
    dest: /tmp/vault_{{ vault_version }}_SHA256SUMS
    mode: '0440'
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | Get checksum of Vault zip"
  ansible.builtin.stat:
    path: /tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    checksum_algorithm: sha256
    get_checksum: true
  register: zip_checkum
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | Get checksum of Vault official repo"
  ansible.builtin.shell: "{{ vault_extract_checksum_cmd }}"
  register: checksum_output
  changed_when: checksum_output.rc != 0
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | Verify sha256sum"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout
    - zip_checkum.stat.checksum != checksum_output.stdout

- name: "Vault | Upgrade | Download and extract new version"
  ansible.builtin.unarchive:
    src: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
    dest: "{{ vault_path }}"
    remote_src: true
  notify: "Vault_restart"
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | Clean tmp files"
  ansible.builtin.file:
    path: "{{ item }}"
  loop:
    - /tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip
    - /tmp/vault_{{ vault_version }}_SHA256SUMS
  when:
    - vault_node_role == 'server'
    - vault_version is not in vault_installed_version.stdout

- name: "Vault | Upgrade | No upgrade needed"
  ansible.builtin.debug:
    msg: "Vault is already up to date in version {{ vault_version }}"
  when:
    - vault_node_role == 'server'
    - vault_version is in vault_installed_version.stdout
